In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape  #4 rows 1 column #1dimenstional array

(4,)

In [5]:
lst1=[22,44,798,88]
lst2=[125,789,556,563]
lst3=[112,55,45,4523]
arr1=np.array([lst1,lst2,lst3])

In [6]:
arr1


array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [7]:
arr1.size

12

In [8]:
arr1.ndim  #number of dimentions

2

In [9]:
arr1.dtype

dtype('int32')

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.shape    #3ROWS AND 5 COLUMNS #2 dimentional array

(3, 4)

In [12]:
arr1.reshape(4,3) #always number of element should be  equal when reshape

array([[  22,   44,  798],
       [  88,  125,  789],
       [ 556,  563,  112],
       [  55,   45, 4523]])

In [13]:
a_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a_3d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a_3d_array.ndim


3

In [15]:
a_3d_array.shape

(2, 2, 2)

# Indexing

In [16]:
arr1

array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [17]:
array1d=np.array([12,1,45,125,12])

In [18]:
array1d

array([ 12,   1,  45, 125,  12])

In [19]:
array1d[2]

45

In [20]:
arr1

array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [81]:
arr1[2:]

array([[ 112,   55,   45, 4523]])

In [21]:
arr1[:,:]

array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [22]:
arr1[0:2,0:3]  #zero row - 1st row and zero column - 2nd column

array([[ 22,  44, 798],
       [125, 789, 556]])

###  0:2 = 0 - 1st all columns <-----> 1: = 1st column and all the other columns. No upper limit

In [85]:
arr1

array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [23]:
arr1[1:,2:]  

array([[ 556,  563],
       [  45, 4523]])

In [24]:
arr1[1:,1:2] #1 and 2nd row,,, then 1st and column

array([[789],
       [ 55]])

In [25]:
arr3=np.arange(0,10)
arr3  #arange use for create 1 dimentional array. Array starts with 0 and ends with 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr4=np.arange(0,100,step=5)
arr4        #creat 1 dimentional array 0-100 but 5 gunakara

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [27]:
val=5
arr1<val

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
arr1

array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [29]:
value=100
arr1<value

array([[ True,  True, False,  True],
       [False, False, False, False],
       [False,  True,  True, False]])

In [30]:
arr1[3:1,2:0]

array([], shape=(0, 0), dtype=int32)

In [31]:
arr10=arr1.copy()
arr10


array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [32]:
arr10/10


array([[  2.2,   4.4,  79.8,   8.8],
       [ 12.5,  78.9,  55.6,  56.3],
       [ 11.2,   5.5,   4.5, 452.3]])

In [33]:
arr1<100

array([[ True,  True, False,  True],
       [False, False, False, False],
       [False,  True,  True, False]])

In [34]:
arr1.size

12

In [35]:
mylist1=[12,13,14]
mylist2=[55,48,78]
mylist3=[111,526,456]
myarr=np.array([mylist1,mylist2,mylist3])

In [36]:
myarr

array([[ 12,  13,  14],
       [ 55,  48,  78],
       [111, 526, 456]])

In [37]:
mylist4=[120,130,140]
mylist5=[505,408,708]
mylist6=[11,56,45]
myarr1=np.array([mylist4,mylist5,mylist6])

In [38]:
myarr1

array([[120, 130, 140],
       [505, 408, 708],
       [ 11,  56,  45]])

In [39]:
mynewarray=myarr + myarr1

In [40]:
mynewarray

array([[132, 143, 154],
       [560, 456, 786],
       [122, 582, 501]])

In [41]:
2*mynewarray

array([[ 264,  286,  308],
       [1120,  912, 1572],
       [ 244, 1164, 1002]])

In [42]:
mynewarray

array([[132, 143, 154],
       [560, 456, 786],
       [122, 582, 501]])

In [43]:
mynewarray2=myarr*myarr1

In [44]:
mynewarray2

array([[ 1440,  1690,  1960],
       [27775, 19584, 55224],
       [ 1221, 29456, 20520]])

In [45]:
newlist=[12,13,14]
newlist1=[12,3,2]
arraymy=np.array([newlist])

In [46]:
arraymy

array([[12, 13, 14]])

In [47]:
arraymy.reshape(3,1)

array([[12],
       [13],
       [14]])

In [48]:
newlist=arraymy.reshape(3,1)

In [49]:
newlist

array([[12],
       [13],
       [14]])

In [50]:
arraynew=np.array(newlist1)

In [51]:
arraynew


array([12,  3,  2])

In [52]:
multiarray=arraynew*newlist

In [53]:
arraynew

array([12,  3,  2])

In [54]:
newlist

array([[12],
       [13],
       [14]])

In [55]:
multiarray

array([[144,  36,  24],
       [156,  39,  26],
       [168,  42,  28]])

In [56]:
multiarray1=newlist*arraynew
multiarray1

array([[144,  36,  24],
       [156,  39,  26],
       [168,  42,  28]])

In [57]:
multiarray2=np.dot(arraynew,newlist)
multiarray2

array([211])

In [58]:
12*12+13*3+14*2

211

In [59]:
arr1[:,:]

array([[  22,   44,  798,   88],
       [ 125,  789,  556,  563],
       [ 112,   55,   45, 4523]])

In [60]:
arr1[0:3,0:3]

array([[ 22,  44, 798],
       [125, 789, 556],
       [112,  55,  45]])

In [61]:
arr5=np.arange(0,11)

In [62]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr5[2:]=125
arr5

array([  0,   1, 125, 125, 125, 125, 125, 125, 125, 125, 125])

In [64]:
np.linspace(1,10,5) #gap is equal....

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [65]:
arr6=np.linspace(1,10,20) #1-10 numbers 20k, a numbers 20 atharema gaps equal
arr6

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [66]:
1-1.47368421

-0.47368421000000005

In [67]:
1.94736842-2.42105263

-0.47368421000000005

In [68]:
arr7=arr6
arr7[5:]=100
arr7

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684, 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ])

In [69]:
arr6 #both array 6 and 7 change. to avoid that we can use copy function

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684, 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ])

In [70]:
arr8=arr6.copy()
arr8

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684, 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ])

In [71]:
arr8[3:]=125

In [72]:
arr8

array([  1.        ,   1.47368421,   1.94736842, 125.        ,
       125.        , 125.        , 125.        , 125.        ,
       125.        , 125.        , 125.        , 125.        ,
       125.        , 125.        , 125.        , 125.        ,
       125.        , 125.        , 125.        , 125.        ])

In [73]:
arr6

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684, 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ])

In [74]:
np.ones(4,dtype=int) #4rows and 1 column

array([1, 1, 1, 1])

In [75]:
np.ones((2,3),dtype=float) #2rows and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.random.rand(3,3) #check this

array([[0.03131312, 0.57046004, 0.25734216],
       [0.33520914, 0.66073414, 0.80555101],
       [0.43366659, 0.27464497, 0.61175641]])

In [77]:
np.random.randint(0,100,8)

array([78, 54, 89, 26, 62, 75, 44, 51])

In [78]:
np.random.randint(0,100,8).reshape(4,2)

array([[39, 43],
       [ 2, 91],
       [59, 87],
       [46, 57]])

In [79]:
np.random.randint(0,100,8).reshape(2,4)

array([[87, 69, 68, 73],
       [66, 14, 95, 31]])