In [22]:
import pandas as pd
import os
import numpy as np
csvopen="E:\CODEZ\Data Science\Python\Data Sets\archive\netflix.csv"

# Data Frames.. Combination of many columns and many rows

# Data Series can be either one row or one column

# If more than one row or one clumn its a data frame

In [2]:
df=pd.read_csv(r"E:\CODEZ\Data Science\Python\Data Sets\archive\netflix.csv")
df.head()

title rating  \
0           White Chicks  PG-13   
1    Lucky Number Slevin      R   
2         Grey's Anatomy  TV-14   
3           Prison Break  TV-14   
4  How I Met Your Mother  TV-PG   

                                         ratingLevel  ratingDescription  \
0  crude and sexual humor, language and some drug...                 80   
1  strong violence, sexual content and adult lang...                100   
2  Parents strongly cautioned. May be unsuitable ...                 90   
3  Parents strongly cautioned. May be unsuitable ...                 90   
4  Parental guidance suggested. May not be suitab...                 70   

   release year  user rating score  user rating size  
0          2004               82.0                80  
1          2006                NaN                82  
2          2016               98.0                80  
3          2008               98.0                80  
4          2014               94.0                80

In [3]:
df.iloc[0,0]

'White Chicks'

In [4]:
df.iloc[2,1]

'TV-14'

In [5]:
df.loc[0:3,"title"]

0           White Chicks
1    Lucky Number Slevin
2         Grey's Anatomy
3           Prison Break
Name: title, dtype: object

In [11]:
twoDarray=np.arange(0,20).reshape(5,4)
twoDarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
df=pd.DataFrame(twoDarray,index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

# When Create data frames should enter data then index and column



In [14]:
df.loc["Row1"]  ##Accessign the elements

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [15]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [55]:
df.to_csv("Test1.csv") ##df datas save into Test1 CSV file. Create new CSV

In [59]:
df["Column3"] #only for coulmn. Type is series

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Column3, dtype: int32

In [60]:
df[["Column1","Column2"]] #Should have to create list

Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        5
Row4       12       13
Row5       16       17

In [61]:
df[["Column1","Column2" ,"Column3"]]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        5       10
Row4       12       13       14
Row5       16       17       18

# Two ways to access elements.
## 1.) loc - row index
## 2.) iloc - index loc (Row and Column index)

In [20]:
df.loc["Row1"]

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [21]:
type(df.loc["Row1"])  #Data Series. 

pandas.core.series.Series

In [24]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
df.iloc[0:3,0:3] #First 3 column and row.... If we want first Row second Row and Third Row. Indexing starts in zero. Zero to 3. it gives 0,1,2

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10

In [26]:
type(df.iloc[0:3,0:3])

pandas.core.frame.DataFrame

In [28]:
df.iloc[0:1,0:1]

Column1
Row1        0

In [29]:
type(df.iloc[0:1,0:1])

pandas.core.frame.DataFrame

In [30]:
df.iloc[0:1]

Column1  Column2  Column3  Column4
Row1        0        1        2        3

In [31]:
type(df.iloc[0:1])

pandas.core.frame.DataFrame

In [32]:
df.iloc[0:2,0]

Row1    0
Row2    4
Name: Column1, dtype: int32

In [38]:
type(df.iloc[0:2,0])

pandas.core.series.Series

In [39]:
df.iloc[:,1:] #Skip Column 1

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [40]:
df.iloc[1:,:] #Skip Row 1. Means Start with Row1(According to index)

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [37]:
#Convert Data Frames into Array

df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [45]:
df.iloc[:,:].values.shape

(5, 4)

In [46]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [42]:
df.isnull().sum() # Check how many null values in owr data set. Not zero(0)> Its like how many missing data

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [44]:
df["Column1"].value_counts() #How many unique values in our column1. 1 means it present 1 time

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [47]:
df["Column1"].unique() #Unique values. if there any repeated value its not shown here

array([ 0,  4,  8, 12, 16])

In [48]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [49]:
df.iloc[2:3,1:2]

Column2
Row3        9

In [50]:
df.iloc[2:3,1:2]=5

In [51]:
df

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        5       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [53]:
df["Column2"].unique() #5 datas. but shows here 4. bcz 5 repeated

array([ 1,  5, 13, 17])

In [54]:
df["Column2"].value_counts() 

5     2
13    1
17    1
1     1
Name: Column2, dtype: int64